export const TRANSACTIONS = [
  {
    category: "meal",
    title: "Обед в бистро",
    date: new Date(2025, 6, 30),
    amount: -500,
  },
  {
    category: "products",
    title: "Покупка продуктов в пятёрочке",
    date: new Date(2025, 6, 29),
    amount: -1432.5,
  },
  {
    category: "transport",
    title: "Метро",
    date: new Date(2025, 6, 28),
    amount: -60,
  },
  {
    category: "games",
    title: "Кино",
    date: new Date(2025, 6, 28),
    amount: -700,
  },
  {
    category: "meal",
    title: "Доставка суши",
    date: new Date(2025, 6, 27),
    amount: -1200,
  },
  {
    category: "products",
    title: "Лента — недельный запас",
    date: new Date(2025, 6, 26),
    amount: -2300,
  },
  {
    category: "clothes",
    title: "Футболка в H&M",
    date: new Date(2025, 6, 25),
    amount: -999,
  },
  {
    category: "meal",
    title: "Кофе и круассан",
    date: new Date(2025, 6, 25),
    amount: -350,
  },
  {
    category: "transport",
    title: "Такси до дома",
    date: new Date(2025, 6, 24),
    amount: -450,
  },
  {
    category: "house",
    title: "Оплата ЖКХ",
    date: new Date(2025, 6, 23),
    amount: -5400,
  },
  {
    category: "medicine",
    title: "Аптека",
    date: new Date(2025, 6, 22),
    amount: -860,
  },
  {
    category: "house",
    title: "Покупка посуды в Икеа",
    date: new Date(2025, 6, 21),
    amount: -1800,
  },
  {
    category: "person",
    title: "Моргунец Михаил",
    date: new Date(2025, 6, 20),
    amount: 300,
  },
  {
    category: "connection",
    title: "Мобильная связь",
    date: new Date(2025, 6, 20),
    amount: -300,
  },
  {
    category: "meal",
    title: "Пицца на вечер",
    date: new Date(2025, 6, 19),
    amount: -1100,
  },
  {
    category: "products",
    title: "Фрукты на рынке",
    date: new Date(2025, 6, 18),
    amount: -670,
  },
  {
    category: "transport",
    title: "Пополнение транспортной карты",
    date: new Date(2025, 6, 17),
    amount: -1000,
  },
  {
    category: "games",
    title: "Steam — игра",
    date: new Date(2025, 6, 17),
    amount: -1200,
  },
  {
    category: "clothes",
    title: "Кроссовки",
    date: new Date(2025, 6, 16),
    amount: -4500,
  },
  {
    category: "meal",
    title: "Обед в столовой",
    date: new Date(2025, 6, 15),
    amount: -300,
  },
  {
    category: "products",
    title: "Закупка на выходные",
    date: new Date(2025, 6, 14),
    amount: -1800,
  },
  {
    category: "transport",
    title: "Такси на вокзал",
    date: new Date(2025, 6, 13),
    amount: -700,
  },
  {
    category: "house",
    title: "Моющее средство и тряпки",
    date: new Date(2025, 6, 13),
    amount: -450,
  },
  {
    category: "medicine",
    title: "Витамины",
    date: new Date(2025, 6, 12),
    amount: -950,
  },
  {
    category: "connection",
    title: "Интернет",
    date: new Date(2025, 6, 11),
    amount: -650,
  },
  {
    category: "person",
    title: "Подарок другу",
    date: new Date(2025, 6, 11),
    amount: -1500,
  },
  {
    category: "games",
    title: "Кинотеатр IMAX",
    date: new Date(2025, 6, 10),
    amount: -1000,
  },
  {
    category: "clothes",
    title: "Штаны в Заре",
    date: new Date(2025, 6, 9),
    amount: -2300,
  },
  {
    category: "meal",
    title: "Шаурма",
    date: new Date(2025, 6, 8),
    amount: -250,
  },
  {
    category: "transport",
    title: "Автобус до дачи",
    date: new Date(2025, 6, 7),
    amount: -200,
  },
  {
    category: "house",
    title: "Оплата интернета",
    date: new Date(2025, 6, 6),
    amount: -900,
  },
  {
    category: "medicine",
    title: "Капли для носа",
    date: new Date(2025, 6, 5),
    amount: -300,
  },
  {
    category: "connection",
    title: "Дополнительный пакет интернета",
    date: new Date(2025, 6, 4),
    amount: -100,
  },
  {
    category: "person",
    title: "Перевод родителям",
    date: new Date(2025, 6, 3),
    amount: -5000,
  },
];
